# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_countWindow(object):
    def setupUi(self, countWindow):
        countWindow.setObjectName("countWindow")
        countWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(countWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 180, 150, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 240, 150, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
       
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 240, 111, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
       
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 300, 150, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        
        
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 300, 111, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 360, 150, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        
        
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 360, 111, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 420, 150, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        
        
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 420, 111, 41))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(325, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")

        countWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(countWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        countWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(countWindow)
        self.statusbar.setObjectName("statusbar")
        countWindow.setStatusBar(self.statusbar)

        self.retranslateUi(countWindow)
        QtCore.QMetaObject.connectSlotsByName(countWindow)

    def retranslateUi(self, countWindow):
        _translate = QtCore.QCoreApplication.translate
        countWindow.setWindowTitle(_translate("countWindow", "Total"))
        
        self.label.setText(_translate("countWindow", " time："))
        self.label_2.setText(_translate("countWindow", "score ："))
        
        self.label_5.setText(_translate("countWindow", "年齡預測 ："))
        
        self.label_6.setText(_translate("countWindow", "預測中..."))
        self.label_7.setText(_translate("countWindow", "性別預測 ："))
        self.label_8.setText(_translate("countWindow", "預測中..."))
        self.label_9.setText(_translate("countWindow", "心情預測 ："))
        self.label_10.setText(_translate("countWindow", "預測中..."))
        self.pushButton.setText(_translate("countWindow", "確認"))
