# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_accountwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_accountWindow(object):
    def setupUi(self, create_accountWindow):
        create_accountWindow.setObjectName("create_accountWindow")
        create_accountWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(create_accountWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 40, 221, 121))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 180, 101, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 240, 101, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 300, 91, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 370, 58, 15))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 190, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 250, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 310, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(380, 370, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 430, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 430, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 430, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        create_accountWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(create_accountWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        create_accountWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(create_accountWindow)
        self.statusbar.setObjectName("statusbar")
        create_accountWindow.setStatusBar(self.statusbar)

        self.retranslateUi(create_accountWindow)
        QtCore.QMetaObject.connectSlotsByName(create_accountWindow)

    def retranslateUi(self, create_accountWindow):
        _translate = QtCore.QCoreApplication.translate
        create_accountWindow.setWindowTitle(_translate("create_accountWindow", "MainWindow"))
        self.label.setText(_translate("create_accountWindow", "建立帳戶"))
        self.label_2.setText(_translate("create_accountWindow", "請輸入帳號:"))
        self.label_3.setText(_translate("create_accountWindow", "請輸入密碼:"))
        self.label_4.setText(_translate("create_accountWindow", "確認密碼:"))
        self.label_5.setText(_translate("create_accountWindow", "誆稱:"))
        self.pushButton.setText(_translate("create_accountWindow", "確認"))
        self.pushButton_2.setText(_translate("create_accountWindow", "取消"))
        self.pushButton_3.setText(_translate("create_accountWindow", "清除"))
