# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont


class Ui_rankWindow(object):
    def setupUi(self, rankWindow):
        rankWindow.setObjectName("rankWindow")
        rankWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(rankWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 80, 200, 30))
        self.label.setObjectName("label")
        self.label.setFont(QFont('Arial', 15))
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(320, 150, 70, 20))
        self.label_1.setObjectName("label_1")
        self.label_1.setFont(QFont('Arial', 10))
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 150, 70, 20))
        self.label_6.setObjectName("label_6")
        self.label_6.setFont(QFont('Arial', 10))
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 220, 70, 20))
        self.label_2.setObjectName("label_2")
        self.label_2.setFont(QFont('Arial', 10))
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(380, 220, 70, 20))
        self.label_7.setObjectName("label_7")
        self.label_7.setFont(QFont('Arial', 10))
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 290, 70, 20))
        self.label_3.setObjectName("label_3")
        self.label_3.setFont(QFont('Arial', 10))
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(380, 290, 70, 20))
        self.label_8.setObjectName("label_8")
        self.label_8.setFont(QFont('Arial', 10))
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 360, 70, 20))
        self.label_4.setObjectName("label_4")
        self.label_4.setFont(QFont('Arial', 10))
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(380, 360, 70, 20))
        self.label_9.setObjectName("label_9")
        self.label_9.setFont(QFont('Arial', 10))
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 430, 70, 20))
        self.label_5.setObjectName("label_5")
        self.label_5.setFont(QFont('Arial', 10))
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(380, 430, 70, 20))
        self.label_10.setObjectName("label_10")
        self.label_10.setFont(QFont('Arial', 10))
        rankWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rankWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        rankWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rankWindow)
        self.statusbar.setObjectName("statusbar")
        rankWindow.setStatusBar(self.statusbar)

        self.retranslateUi(rankWindow)
        QtCore.QMetaObject.connectSlotsByName(rankWindow)

    def retranslateUi(self, rankWindow):
        _translate = QtCore.QCoreApplication.translate
        rankWindow.setWindowTitle(_translate("rankWindow", "MainWindow"))
        self.label.setText(_translate("rankWindow", "Rank(Normal mode)"))
        self.label_1.setText(_translate("rankWindow", "1."))
        self.label_6.setText(_translate("rankWindow", "None"))
        self.label_2.setText(_translate("rankWindow", "2."))
        self.label_7.setText(_translate("rankWindow", "None"))
        self.label_3.setText(_translate("rankWindow", "3."))
        self.label_8.setText(_translate("rankWindow", "None"))
        self.label_4.setText(_translate("rankWindow", "4."))
        self.label_9.setText(_translate("rankWindow", "None"))
        self.label_5.setText(_translate("rankWindow", "5."))
        self.label_10.setText(_translate("rankWindow", "None"))
